### ISSUE TITLE
(Question) Influences

### ISSUE THREAD

**Issue by hardBSDk** [cl91/NeptuneOS#15]
- How is Neptune OS related with Wine?

AFAIK Wine already implements the Windows kernel on user-space (wineserver), thus I think Neptune is seL4-specific.

- How much it's different from ReactOS ?

**Comment by cl91** [comment]
> Wine already implements the Windows kernel on user-space (wineserver)
Yes, in fact wine has a very similar architecture to us. However, wine's implementation depends on the POSIX API which is not available on seL4. POSIX is a very fat layer of API so implementing it first on seL4 will be more work than starting from scratch. Additionally, wine does not implement any of the device driver interfaces provided by the NT kernel (this is in fact the bigger part of the project).

> How much it's different from ReactOS?
For userland (by 'userland' I mean the components running in userspace of a traditional, non-microkernel OS), I'm hoping to achieve binary compatibility with ReactOS, although it's a long shot. For device drivers, due to the architectural differences there won't be any binary compatibility, but I'm hoping that once the system matures the porting effort to port a ReactOS driver to NeptuneOS will be low.

I'm now working on file systems, in particular porting the fatfs driver (see https://github.com/cl91/NeptuneOS/tree/fat). The progress is a little slow due to my day job but I'm hoping to quit my day job soon to work on NeptuneOS more.

**Comment by cl91** [comment]
I think the questions are answered now so I'm closing the issue.
